        <center>
            <a href="//www.sibi.usp.br/" title="Voltar para a página principal">
                <img src="//www.sibi.usp.br/wp-content/themes/sibi-usp/assets/img/logotipo-sibi-usp.jpg" alt="Logotipo SIBiUSP">
            </a>
        </center>
        <div class="barrausp"><p>&nbsp;<br/>&nbsp;<br/>&nbsp;</p></div>
        <div class="uk-container uk-container-center uk-margin-large-bottom">
